---
Name: emteknetnz-query-counter
After: databaseconnectors
---
SilverStripe\Core\Injector\Injector:
  MySQLiConnector:
    class: 'emteknetnz\DBQueryCounter\DBQueryMySQLiConnector'
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        DBQueryMiddleware: '%$emteknetnz\DBQueryCounter\DBQueryMiddleware'
